
const characters=[
['Honza Dvořák','Matěj Hádek, Branislav Holiček, Jiří Novák, Zdeněk Piškula','Člen rodiny Dvořákových, jehož životní etapy seriál sleduje v různých věkových obdobích.','syn a později dospělý člen rodiny'],
['Lucka Francová','Lucie Štěpánková, Eliška Křenková, Eliška Zbranková','Výrazná postava mladší generace. Její příběh se postupně propojuje s rodinou Dvořákových.','vztahy, rodina a dospívání'],
['Babička Běta','Nina Divíšková','Rodinná autorita a výrazná představitelka starší generace.','tradice, rodina a paměť'],
['František Kopecký','Radoslav Brzobohatý','Postava z okruhu rodiny, která pomáhá rozšiřovat příběh za hranice samotných Dvořákových.','rodinné a společenské vztahy'],
['Josef Dvořák','Svatopluk Skopal','Praktický a výrazný člen rodiny. Jeho pracovní i osobní problémy často odrážejí dobu, ve které rodina žije.','práce, rodina, společnost'],
['Jana Dvořáková','Veronika Freimanová','Jedna z klíčových ženských postav rodiny Dvořákových.','rodina a každodenní život'],
['Karel Dvořák','Roman Vojtek','Ústřední postava, jejíž životní cesta začíná v šedesátých letech a pokračuje přes zásadní společenské změny.','technika, práce, rodina'],
['Eva Dvořáková','Andrea Kerestešová','Karlova partnerka a později manželka. Její životní rozhodnutí významně ovlivňují hlavní dějovou linii.','rodina, vztahy, osobní rozhodnutí'],
['Matěj Dvořák','Štěpán Benoni, Štěpán Krtička, Filip Antonio','Postava z další generace Dvořákových, kterou sledujeme v různých věkových obdobích.','mladší generace'],
['Majda Sovová','Lucie Šteflová','Postava z okruhu Sovových a Dvořákových.','vztahy a rodinné vazby'],
['Zuzka Sovová, rozená Dvořáková','Hana Vagnerová, Andrea Nováková','Dcera Dvořákových, jejíž životní příběh propojuje rodinnou linku s další generací.','rodina a dospívání'],
['Tonda Sova','Jaromír Nosek','Výrazná postava mladší generace a součást rodinného okruhu.','mladší generace'],
['Radim Dvořák','David Prachař','Člen širší rodiny Dvořákových.','rodinné vztahy'],
['Milada Dvořáková','Mahulena Bočanová','Členka rodiny Dvořákových.','rodina'],
['Mikuláš Dvořák','Pavel Trávníček','Příbuzný, který do příběhu přináší i pohled na život mimo Československo.','rodina a zahraničí'],
['Renáta Dvořáková','Lenka Zahradnická','Postava, která se v rodinném příběhu výrazněji uplatňuje v pozdějších dějových liniích.','rodina a vztahy'],
['Katarína Martináková','Milka Minichová','Postava spojená se slovenskou částí příběhu.','Česko-slovenské vztahy'],
['Hynek Kupsa','Josef Polášek','Výrazná vedlejší postava.','práce a vztahy'],
['Mária Martináková','Marta Sládečková','Postava z okruhu Martinákových.','rodina a vztahy'],
['Alexander Zapletal','David Kraus','Vedlejší postava, která rozšiřuje společenský svět seriálu.','společenské vztahy'],
['Kamila Ptáčková','Zuzana Kajnarová','Postava z širšího okruhu příběhu.','vztahy a každodennost'],
['Iveta Hájková','Jana Bernášková','Výrazná vedlejší postava s vlastním životním příběhem.','vztahy'],
['Veronika Francová, rozená Malá','Alžběta Stanková','Postava propojující rodinný a partnerský svět seriálu.','rodina a vztahy'],
['Jaroslav Franc','Ondřej Veselý','Člen okruhu Francových.','rodinné vztahy'],
['Václav Hora','Tomáš Töpfer','Výrazná vedlejší postava.','společenské prostředí'],
['Martina Povolná','Olga Lounová','Vedlejší postava.','vztahy'],
['Lubomír Karpíšek','Ján Jackuliak','Vedlejší postava z širšího společenského okruhu.','práce a společnost'],
['Věra Nedbalová','Veronika Žilková','Výrazná vedlejší postava.','rodinné a společenské vztahy'],
['Radek Krása','Jiří Štěpnička','Vedlejší postava.','společenské prostředí'],
['Mirek Kozel','Jan Šťastný','Vedlejší postava.','společenské prostředí'],
['Ivan Brož','Antonín Procházka','Vedlejší postava.','společenské prostředí'],
['Marek Oplatka','Ladislav Hampl','Vedlejší postava.','společenské prostředí'],
['Jaroslava Plachá','Nela Boudová','Vedlejší postava.','společenské prostředí']
];
